linked_data_field.linked_data_endpoint.*:
  type: config_entity
  label: 'Linked Data Lookup Endpoint config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'Endpoint Type'
    base_url:
      type: string
      label: 'Endpoint base URL'
    result_json_path:
      type: string
      label: 'Result Items JSON Path'
    label_key:
      type: string
      label: 'Name JSON key'
    url_key:
      type: string
      label: 'URL JSON key'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: '[%parent.%parent.%type].third_party.[%key]'
    uuid:
      type: string
